#!/bin/sh

usage()
{
	echo "usage: $0 [--cflags] [--libs] [--version]"
	exit 0
}

cflags=no
libs=no
version=no

test "$1" || usage

while test "$1"; do
	case "$1" in
	--cflags )
		cflags=yes
		;;
	--libs )
		libs=yes
		;;
	--version )
		version=yes
		;;
	* )
		usage
		;;
	esac
	shift
done

test "$cflags" = yes && cat << FOO
-I/home/shubham/Documents/shubham/ksmppd/build/include/kannel -g -O2 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_LARGE_FILES= -I/usr/include/libxml2 -I/usr/include/openssl -I/usr/include/mysql
FOO

test "$libs" = yes && cat << FOO
-L/home/shubham/Documents/shubham/ksmppd/build/lib -lgw -lwap -lgwlib -lmysqlclient -lssl -lrt -lresolv -lnsl -lm  -lpthread -lxml2 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -lcrypto -lssl -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -latomic -lssl -lcrypto -ldl
FOO

test "$version" = yes && cat << FOO
svn-r5297M
FOO

